[package]
name = "definy-server"
version = "0.1.0"
edition = "2024"

[lib]
name = "definy_server"
path = "src/lib.rs"

[[bin]]
name = "definy_server"
path = "src/main.rs"

[dependencies]
axum = { workspace = true }
hyper = { workspace = true, features = ["full"] }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true, features = ["sync"] }
http-body-util = { workspace = true }
hyper-util = { workspace = true, features = ["full"] }
definy-ui = { workspace = true }
definy-core = { workspace = true }
definy-event = { workspace = true, features = ["utoipa"] }
dioxus = { workspace = true, features = ["macro", "hooks"] }
dioxus-fullstack = { workspace = true }
dioxus-ssr = { workspace = true }
sha2 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_cbor = { workspace = true }
prost = { workspace = true }
surrealdb = { workspace = true, features = [
  "kv-mem",
  "protocol-ws",
  "protocol-http",
  "kv-surrealkv",
] }
anyhow = { workspace = true }
ed25519-dalek = { workspace = true }
hex = { workspace = true }
base64 = { workspace = true }
serde_urlencoded = { workspace = true }
strum = { workspace = true, features = ["derive"] }
strum_macros = { workspace = true }
url = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
rand = { workspace = true }
tower = { workspace = true, features = ["util"] }
tower-http = { workspace = true, features = ["cors"] }
utoipa = { workspace = true, features = ["axum_extras", "chrono"] }
utoipa-swagger-ui = { workspace = true, features = ["axum"] }
utoipa-axum = { workspace = true }
