[package]
name = "definy-server"
version = "0.1.0"
edition = "2024"

[lib]
name = "definy_server"
path = "src/lib.rs"

[[bin]]
name = "definy_server"
path = "src/main.rs"

[dependencies]
axum = "0.8"
hyper = { workspace = true, features = ["full"] }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
http-body-util = { workspace = true }
hyper-util = { workspace = true, features = ["full"] }
definy-ui = { workspace = true }
definy-event = { workspace = true, features = ["utoipa"] }
dioxus = { workspace = true, features = ["macro", "hooks"] }
dioxus-fullstack = { workspace = true }
dioxus-ssr = { workspace = true }
sha2 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_cbor = { workspace = true }
surrealdb = { version = "3.2.4", features = [
  "kv-mem",
  "protocol-ws",
  "protocol-http",
  "kv-surrealkv",
] }
anyhow = { workspace = true }
ed25519-dalek = { workspace = true }
hex = "0.4.3"
base64 = { workspace = true }
serde_urlencoded = { workspace = true }
strum = { workspace = true, features = ["derive"] }
strum_macros = { workspace = true }
url = "2.5.8"
chrono = { workspace = true, features = ["serde"] }
rand = "0.8.8"
tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.6", features = ["cors"] }
utoipa = { workspace = true, features = ["axum_extras", "chrono"] }
utoipa-swagger-ui = { version = "9.0", features = ["axum"] }
utoipa-axum = "0.2"
