-- generated by definy. Do not edit!
module Sub.Lib (floatSample, partName, nonEmptyTextSampleMimeType) where

import Data.String.NonEmpty as M0
import Prim as M1
import Type.Proxy as M2

-- | 浮動小数点数のサンプル
floatSample :: M1.String
floatSample = "unsupported float"

-- | part description
partName :: M1.String
partName = "unsupported float"

-- | part description
nonEmptyTextSampleMimeType :: M0.NonEmptyString
nonEmptyTextSampleMimeType = (M0.nes) (M2.Proxy :: (M2.Proxy) ("image/png"))

