/* eslint-disable */
/* generated by definy. Do not edit! */


/**
 * 分かりやすい説明文
 */


/**
 * 浮動小数点数のサンプル
 */
export const floatSample: number = "<unknown float64 literal!!!>";


/**
 * part description
 */
export const partName: number = 6.28;


/**
 * part description
 */
export const partName: string = "テキスト";


/**
 * 分かりやすい説明文
 */
export const identifierSample: unknown = unknownPart;
