/* eslint-disable */
/* generated by definy. Do not edit! */


/**
 * description
 */


/**
 * 浮動小数点数のサンプル
 */
export const floatSample: number = 32;


/**
 * part description
 */
export const partName: number = 6.28;


/**
 * part description
 */
export const partName: string = "テキスト";
