/* eslint-disable */
/* generated by definy. Do not edit! */


/**
 * mimetype
 */


/**
 * MIME タイプ https://developer.mozilla.org/ja/docs/Web/HTTP/Basics_of_HTTP/MIME_types  definy, ナルミンチョの創作記録で扱う http のレスポンスで返す content-type
 */
export type mimeType = "png" | "javaScript" | "html" | "json" | "webOpenFontFormat2";


/**
 * png 画像
 */
export const png: string = "image/png";


/**
 * html
 */
export const html: string = "text/html";


/**
 * javaScript
 */
export const javaScript: string = "text/javaScript";


/**
 * json
 */
export const json: string = "application/json";


/**
 * フォント WebOpenFontFormat2
 */
export const woff2: string = "font/woff2";


/**
 * バイナリ形式
 */
export const binary: string = "application/octet-stream";
