/* eslint-disable */
/* generated by definy. Do not edit! */


/**
 * mimetype
 */


/**
 * png 画像
 */
export const png: string = "image/png";


/**
 * html
 */
export const html: string = "text/html";


/**
 * javaScript
 */
export const javaScript: string = "text/javaScript";


/**
 * json
 */
export const json: string = "application/json";


/**
 * フォント WebOpenFontFormat2
 */
export const woff2: string = "font/woff2";


/**
 * バイナリ形式
 */
export const binary: string = "application/octet-stream";
