include: package:flutter_lints/flutter.yaml

linter:
  # https://dart-lang.github.io/linter/lints/
  # から役立ちそうなルールを適宜追加する
  rules:
    - always_use_package_imports
    - avoid_dynamic_calls
    - avoid_type_to_string
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_escaping_inner_quotes
    - avoid_final_parameters # parameter_assignments を指定しているため
    - avoid_implementing_value_types
    - avoid_js_rounded_ints
    - avoid_multiple_declarations_per_line
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_redundant_argument_values
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cascade_invocations
    - conditional_uri_does_not_exist
    - deprecated_consistency
    - directives_ordering
    - do_not_use_environment
    - eol_at_end_of_file
    - leading_newlines_in_multiline_strings
    - no_runtimeType_toString
    - only_throw_errors
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_if_elements_to_conditional_expressions
    - prefer_int_literals
    - prefer_null_aware_method_calls
    - prefer_single_quotes
    - sized_box_shrink_expand
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - use_colored_box
    - use_decorated_box
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_raw_strings
    - use_to_and_as_if_applicable
    - secure_pubspec_urls
    - sort_pub_dependencies

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    parameter_assignments: error
