[application]
name = "definy_client"
default_platform = "fullstack"

[web.app]
title = "definy"

[web.watcher]
reload_html = true
watch_path = ["definy-client", "definy-server", "definy-ui", "definy-event"]
