name: definy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.3
  flutter_web_plugins:
    sdk: flutter
  fast_immutable_collections: ^10.2.4
  simple_graphql_client_gen: ^0.9.2
  qr_flutter: ^4.1.0
  flutter_localizations:
      sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
