/* eslint-disable */
/* generated by definy. Do not edit! */


/**
 * モジュールの説明だよー
 */


/**
 * partDescription
 */
export const _: number = (1+(2+3));


/**
 * **サンプル4パーツの説明文!**
 */
export const sample4Part: number = (3+1);


/**
 * samplePartの説明文 カッコ() や 空白を含めることもできるようになったぞ!
 */
export const samplePart: number = (sample4Part+10);


/**
 * bの説明文 改行有り
 */
export const b: number = (samplePart+1);


/**
 * kの説明文
 */
export const k: number = (samplePart+(1+39));


/**
 * description
 */
export const sample: number = ("<unknown part!!!>"+28);


/**
 * `sampleText`を使ってみる
 */
export const useSampleText: unknown = sampleText;


/**
 * サンプルテキストだ!
 */
export const sampleText: string = "文字列をちゃんと定義できてるかな?";


/**
 * 浮動小数点数リテラルを導入したぞ!
 */
export const sampleFloat64Value: number = 32.324;
