/* eslint-disable */
/* generated by definy. Do not edit! */


/**
 * 分かりやすい説明文
 */


/**
 * 新たな型!
 */
export const sampleType: string = "wip";


/**
 * 浮動小数点数のサンプル
 */
export const floatSample: number = "<unknown float64 literal!!!>";


/**
 * part description
 */
export const partName: number = 6.28;


/**
 * part description
 */
export const nonEmptyTextEmptyErrorTest: string = "<unknown nonEmptyString literal!!!>";


/**
 * part description
 */
export const nonEmptyTextSampleMimeType: string = "image/png";
