use narumincho_vdom::*;

pub fn app(count: i32) -> Node {
    Html::new()
        .children([
            Head::new()
                .children([
                    Title::new().children([text("definy")]).into_node(),
                    Link::new()
                        .rel("icon")
                        .href(include_str!("../../web-distribution/icon.png.sha256"))
                        .into_node(),
                    Script::new()
                        .type_("module")
                        .children([text(format!(
                            "import init from './{}';
init(\"{}\");",
                            include_str!("../../web-distribution/definy_client.js.sha256"),
                            include_str!("../../web-distribution/definy_client_bg.wasm.sha256"),
                        ))])
                        .into_node(),
                ])
                .into_node(),
            Body::new()
                .children([
                    H1::new().children([text("definy")]).into_node(),
                    Button::new()
                        .command_for("create-account-dialog")
                        .command("show-modal")
                        .type_("button")
                        .children([text("アカウント作成")])
                        .into_node(),
                    create_account_dialog(),
                    Button::new()
                        .command("increment")
                        .type_("button")
                        .children([text(format!("count: {}", count))])
                        .into_node(),
                ])
                .into_node(),
        ])
        .into_node()
}

/// アカウント作成ダイアログ
pub fn create_account_dialog() -> Node {
    Dialog::new()
        .id("create-account-dialog")
        .children([
            "アカウント作成ダイアログだよ".to_string().into(),
            Form::new()
                .children([
                    Label::new()
                        .children([
                            text("ユーザー名"),
                            Input::new()
                                .type_("text")
                                .name("username")
                                .autocomplete("username")
                                .required()
                                .into_node(),
                            Label::new()
                                .children([
                                    text("秘密鍵"),
                                    text(
                                        "分散システムのため秘密鍵を失うとログインすることができなくなってしまいます",
                                    ),
                                    Input::new()
                                        .type_("password")
                                        .name("password")
                                        .autocomplete("new-password")
                                        .required()
                                        .readonly()
                                        .into_node(),
                                ])
                                .into_node(),
                        ])
                        .into_node(),
                    Button::new()
                        .type_("submit")
                        .children([text("送信")])
                        .into_node(),
                ])
                .into_node(),
            Button::new()
                .command_for("create-account-dialog")
                .command("close")
                .type_("button")
                .children([text("閉じる")])
                .into_node(),
        ])
        .into_node()
}
