/* eslint-disable */
/* generated by definy. Do not edit! */


/**
 * 分かりやすい説明文
 */


/**
 * 浮動小数点数のサンプル
 */
export const floatSample = "<unknown float64 literal!!!>";


/**
 * part description
 */
export const partName = 6.28;


/**
 * part description
 */
export const nonEmptyTextSampleMimeType = "image/png";
