/* eslint-disable */
/* generated by definy. Do not edit! */



/**
 * クライアントでファイルを取得するのに使うURL
 */
export const staticResourceUrl: { 
/**
 * static な ファイル の "battle.png"をリクエストするためのURL. ファイルのハッシュ値は "b498aff8917d349aa0f9b3a41a0d6a5b7093caea175873b4bc77a467ef67d499"
 */
readonly battlePng: URL; 
/**
 * static な ファイル の "color.png"をリクエストするためのURL. ファイルのハッシュ値は "d1f295174ec13a77811ff1b9e4c58377f50c444ba1bea8f9587448f2720c655c"
 */
readonly colorPng: URL; 
/**
 * static な ファイル の "definy20210811.png"をリクエストするためのURL. ファイルのハッシュ値は "33b80a0844230e60044b9891dc2fbefc3960e7995913e10928ca17852a8c3ce7"
 */
readonly definy20210811Png: URL; 
/**
 * static な ファイル の "desired_route_title.png"をリクエストするためのURL. ファイルのハッシュ値は "6959cae6bdab07e752157c9077d1153b0a61d525869b7ecef6630b8cde4815b0"
 */
readonly desired_route_titlePng: URL; 
/**
 * static な ファイル の "font.png"をリクエストするためのURL. ファイルのハッシュ値は "68c380d905ce9e1f8043c3f5c3c7f3fd51b0156d49cd36912aaf94c7f368c28a"
 */
readonly fontPng: URL; 
/**
 * static な ファイル の "grape_svg_code.png"をリクエストするためのURL. ファイルのハッシュ値は "ddc034ae2b5d07e6ec33076a3a45bd9772c6670f53b14ddd30c0b51f2b97c7fb"
 */
readonly grape_svg_codePng: URL; 
/**
 * static な ファイル の "gravity_star.png"をリクエストするためのURL. ファイルのハッシュ値は "68800d65e7bba25db6a2e5e5d2001e275969f10e653d34233989543090809dc2"
 */
readonly gravity_starPng: URL; 
/**
 * static な ファイル の "henkan.png"をリクエストするためのURL. ファイルのハッシュ値は "fbeaa96a4aa8321b5f81238cad963e5e2eb1a8ef8f39f169b5a015bca7f06bb2"
 */
readonly henkanPng: URL; 
/**
 * static な ファイル の "icon.png"をリクエストするためのURL. ファイルのハッシュ値は "fe793a7f2e27cb8cfe578e5dff35315e2ba9c2544dcb250d3e9b78ca00a5b959"
 */
readonly iconPng: URL; 
/**
 * static な ファイル の "kamausagi.png"をリクエストするためのURL. ファイルのハッシュ値は "6939a60eff9d66c18333d1cd28cdb052ed5d6ed8e0c933b9bfa2780596f41853"
 */
readonly kamausagiPng: URL; 
/**
 * static な ファイル の "list_ui.png"をリクエストするためのURL. ファイルのハッシュ値は "7d1f910bbaccf3362282d509b606084ca93b8e2dd8055283280b421ae5d5c50a"
 */
readonly list_uiPng: URL; 
/**
 * static な ファイル の "powershell_icon.png"をリクエストするためのURL. ファイルのハッシュ値は "3e53209d83848dffa23b7cbbdca35a735c55a6b55601cdedd303a3f90d559fe3"
 */
readonly powershell_iconPng: URL; 
/**
 * static な ファイル の "star.png"をリクエストするためのURL. ファイルのハッシュ値は "f0e7afe9457c2dc0c117934e3e584001d1fa7c910ec912ac1260179ab1dac8db"
 */
readonly starPng: URL; 
/**
 * static な ファイル の "svg_basic.png"をリクエストするためのURL. ファイルのハッシュ値は "07eb3d10e2f339ab8574ffa8a3f9f15bfd6f51518ef24bb38ae92d54deb9510a"
 */
readonly svg_basicPng: URL; 
/**
 * static な ファイル の "tsukumart.png"をリクエストするためのURL. ファイルのハッシュ値は "2df345d24aef7080b8f64a69a022b8e1d7968ebfd8e93e42c1c6e7a9cb088d64"
 */
readonly tsukumartPng: URL; 
/**
 * static な ファイル の "window.png"をリクエストするためのURL. ファイルのハッシュ値は "3162cd943ef3c3c7681b84acb99e54ada924dccdbcda8ee090d31e28efda1dc8"
 */
readonly windowPng: URL } = { battlePng: new URL("http://localhost:8080/b498aff8917d349aa0f9b3a41a0d6a5b7093caea175873b4bc77a467ef67d499"), colorPng: new URL("http://localhost:8080/d1f295174ec13a77811ff1b9e4c58377f50c444ba1bea8f9587448f2720c655c"), definy20210811Png: new URL("http://localhost:8080/33b80a0844230e60044b9891dc2fbefc3960e7995913e10928ca17852a8c3ce7"), desired_route_titlePng: new URL("http://localhost:8080/6959cae6bdab07e752157c9077d1153b0a61d525869b7ecef6630b8cde4815b0"), fontPng: new URL("http://localhost:8080/68c380d905ce9e1f8043c3f5c3c7f3fd51b0156d49cd36912aaf94c7f368c28a"), grape_svg_codePng: new URL("http://localhost:8080/ddc034ae2b5d07e6ec33076a3a45bd9772c6670f53b14ddd30c0b51f2b97c7fb"), gravity_starPng: new URL("http://localhost:8080/68800d65e7bba25db6a2e5e5d2001e275969f10e653d34233989543090809dc2"), henkanPng: new URL("http://localhost:8080/fbeaa96a4aa8321b5f81238cad963e5e2eb1a8ef8f39f169b5a015bca7f06bb2"), iconPng: new URL("http://localhost:8080/fe793a7f2e27cb8cfe578e5dff35315e2ba9c2544dcb250d3e9b78ca00a5b959"), kamausagiPng: new URL("http://localhost:8080/6939a60eff9d66c18333d1cd28cdb052ed5d6ed8e0c933b9bfa2780596f41853"), list_uiPng: new URL("http://localhost:8080/7d1f910bbaccf3362282d509b606084ca93b8e2dd8055283280b421ae5d5c50a"), powershell_iconPng: new URL("http://localhost:8080/3e53209d83848dffa23b7cbbdca35a735c55a6b55601cdedd303a3f90d559fe3"), starPng: new URL("http://localhost:8080/f0e7afe9457c2dc0c117934e3e584001d1fa7c910ec912ac1260179ab1dac8db"), svg_basicPng: new URL("http://localhost:8080/07eb3d10e2f339ab8574ffa8a3f9f15bfd6f51518ef24bb38ae92d54deb9510a"), tsukumartPng: new URL("http://localhost:8080/2df345d24aef7080b8f64a69a022b8e1d7968ebfd8e93e42c1c6e7a9cb088d64"), windowPng: new URL("http://localhost:8080/3162cd943ef3c3c7681b84acb99e54ada924dccdbcda8ee090d31e28efda1dc8") };


