/* eslint-disable */
/* generated by definy. Do not edit! */



/**
 * オリジン (ビルド時にコード生成される)
 */
export const origin: string = "http://localhost:8080";


/**
 * クライアントでファイルを取得するのに使うURL
 */
export const staticResourceUrl: { 
/**
 * static な ファイル の "[object Object]"をリクエストするためのURL. ファイルのハッシュ値は "48e44777ca0ff4251820ce2d233d75698e2d864cf6cea524afb3f97a9e0314f7"
 */
readonly battlePng: URL; 
/**
 * static な ファイル の "[object Object]"をリクエストするためのURL. ファイルのハッシュ値は "ab7d45b15114d96b80f5fafa1047d4a40250ba2e9a83b025c5531af2c4004183"
 */
readonly colorPng: URL; 
/**
 * static な ファイル の "[object Object]"をリクエストするためのURL. ファイルのハッシュ値は "f557481f6f785af8696767ee133e2c869af474f60d2a9ccfdde76499d14e0da9"
 */
readonly definy20210811Png: URL; 
/**
 * static な ファイル の "[object Object]"をリクエストするためのURL. ファイルのハッシュ値は "867692550819f4551fe14145773229b4799f760ccec1534df7e1c8020d92c3c4"
 */
readonly desired_route_titlePng: URL; 
/**
 * static な ファイル の "[object Object]"をリクエストするためのURL. ファイルのハッシュ値は "10c83f6760df0d090d0819f8bcca22f93f014166846baa2514b006b0cf662cec"
 */
readonly fontPng: URL; 
/**
 * static な ファイル の "[object Object]"をリクエストするためのURL. ファイルのハッシュ値は "3015ae6f0ea73c6fc1f464420766f7be17fd7dc745ca51cdfe723d1a60140dfe"
 */
readonly grape_svg_codePng: URL; 
/**
 * static な ファイル の "[object Object]"をリクエストするためのURL. ファイルのハッシュ値は "f6767e80d1ec3f741fcd53319d66a4ce9f55ec76887b2b77eb46e1e1fd0e6923"
 */
readonly gravity_starPng: URL; 
/**
 * static な ファイル の "[object Object]"をリクエストするためのURL. ファイルのハッシュ値は "d56dcc9bfc66e59624f6d41d00c98233e0ffa6676aebcfa05defaf3e178a3bd5"
 */
readonly henkanPng: URL; 
/**
 * static な ファイル の "[object Object]"をリクエストするためのURL. ファイルのハッシュ値は "29f2da92e9d693d41f3c52ab7063ba8e11baffaff2e106434dfbcc6567250576"
 */
readonly iconPng: URL; 
/**
 * static な ファイル の "[object Object]"をリクエストするためのURL. ファイルのハッシュ値は "d0a36b340e666e100ce7774991a7a3f7a806844e64e30dccf7ae40ccf2d5ac56"
 */
readonly kamausagiPng: URL; 
/**
 * static な ファイル の "[object Object]"をリクエストするためのURL. ファイルのハッシュ値は "bacfb0d2a0e64b0c120e4bf9c0428ed9e7090c3f84bb13059b2916e62ad46463"
 */
readonly list_uiPng: URL; 
/**
 * static な ファイル の "[object Object]"をリクエストするためのURL. ファイルのハッシュ値は "92665e160f1dd0852c316b6f80e1664e1f49260f9b8f7cb1f876d49a2490341f"
 */
readonly powershell_iconPng: URL; 
/**
 * static な ファイル の "[object Object]"をリクエストするためのURL. ファイルのハッシュ値は "80e386b255bedcdf3bd2268b58ac4591fa4255d1e76d0c2c2d617151aaa70547"
 */
readonly starPng: URL; 
/**
 * static な ファイル の "[object Object]"をリクエストするためのURL. ファイルのハッシュ値は "0d5c90d7674b01d00e82de645cbff7fbc2640a1ce0af250b59225784b60b3326"
 */
readonly svg_basicPng: URL; 
/**
 * static な ファイル の "[object Object]"をリクエストするためのURL. ファイルのハッシュ値は "610b03d4fb4776b63332d6c70d0cb826ebbca3811ea79de6738afa7e8af9e8ba"
 */
readonly tsukumartPng: URL; 
/**
 * static な ファイル の "[object Object]"をリクエストするためのURL. ファイルのハッシュ値は "1b1abe67660dba0f539455356bebeff7c3b5d0745833ca20811f047524ab3fa6"
 */
readonly windowPng: URL } = { battlePng: new URL("http://localhost:8080/48e44777ca0ff4251820ce2d233d75698e2d864cf6cea524afb3f97a9e0314f7"), colorPng: new URL("http://localhost:8080/ab7d45b15114d96b80f5fafa1047d4a40250ba2e9a83b025c5531af2c4004183"), definy20210811Png: new URL("http://localhost:8080/f557481f6f785af8696767ee133e2c869af474f60d2a9ccfdde76499d14e0da9"), desired_route_titlePng: new URL("http://localhost:8080/867692550819f4551fe14145773229b4799f760ccec1534df7e1c8020d92c3c4"), fontPng: new URL("http://localhost:8080/10c83f6760df0d090d0819f8bcca22f93f014166846baa2514b006b0cf662cec"), grape_svg_codePng: new URL("http://localhost:8080/3015ae6f0ea73c6fc1f464420766f7be17fd7dc745ca51cdfe723d1a60140dfe"), gravity_starPng: new URL("http://localhost:8080/f6767e80d1ec3f741fcd53319d66a4ce9f55ec76887b2b77eb46e1e1fd0e6923"), henkanPng: new URL("http://localhost:8080/d56dcc9bfc66e59624f6d41d00c98233e0ffa6676aebcfa05defaf3e178a3bd5"), iconPng: new URL("http://localhost:8080/29f2da92e9d693d41f3c52ab7063ba8e11baffaff2e106434dfbcc6567250576"), kamausagiPng: new URL("http://localhost:8080/d0a36b340e666e100ce7774991a7a3f7a806844e64e30dccf7ae40ccf2d5ac56"), list_uiPng: new URL("http://localhost:8080/bacfb0d2a0e64b0c120e4bf9c0428ed9e7090c3f84bb13059b2916e62ad46463"), powershell_iconPng: new URL("http://localhost:8080/92665e160f1dd0852c316b6f80e1664e1f49260f9b8f7cb1f876d49a2490341f"), starPng: new URL("http://localhost:8080/80e386b255bedcdf3bd2268b58ac4591fa4255d1e76d0c2c2d617151aaa70547"), svg_basicPng: new URL("http://localhost:8080/0d5c90d7674b01d00e82de645cbff7fbc2640a1ce0af250b59225784b60b3326"), tsukumartPng: new URL("http://localhost:8080/610b03d4fb4776b63332d6c70d0cb826ebbca3811ea79de6738afa7e8af9e8ba"), windowPng: new URL("http://localhost:8080/1b1abe67660dba0f539455356bebeff7c3b5d0745833ca20811f047524ab3fa6") };


