/* eslint-disable */
/* generated by definy. Do not edit! */



/**
 * コード
 */
export const code: string = "module(\n  \"モジュールの説明だよー\",\n  body(\n    part(\n      InvalidPartName,\n      partDescription,\n      add(uint(1), add(uint(2), uint(3))),\n    ),\n    part(sample4Part, \"**サンプル4パーツの説明文!**\", add(uint(3), uint(1))),\n    part(\n      samplePart,\n      \"samplePartの説明文 カッコ() や 空白を含めることもできるようになったぞ!\",\n      add(sample4Part, uint(10)),\n    ),\n    part(b, \"bの説明文 改行有り\", add(samplePart, uint(1))),\n    part(k, \"kの説明文\", add(samplePart, add(uint(1), uint(39)))),\n    part(sample, description, uint(\" 123\")),\n    part(sample, description, add(28, uint(28))),\n  ),\n)\n";
