-- generated by definy. Do not edit!
module CreativeRecord.ClientProgramHashValue (clientProgramHashValue) where

import Data.String.NonEmpty as M0
import Type.Proxy as M1

-- | クライアント向け JavaScript のファイルのハッシュ値
clientProgramHashValue :: M0.NonEmptyString
clientProgramHashValue = (M0.nes) (M1.Proxy :: (M1.Proxy) ("9da0511156a553aac93c73428d988cdc914cd5ab1022319c6041253ae31cdc13"))

