-- generated by definy. Do not edit!
module CreativeRecord.ClientProgramHashValue (clientProgramHashValue) where

import Data.String.NonEmpty as M0
import Type.Proxy as M1

-- | クライアント向け JavaScript のファイルのハッシュ値
clientProgramHashValue :: M0.NonEmptyString
clientProgramHashValue = (M0.nes) (M1.Proxy :: (M1.Proxy) ("6841641e8868a3f90028acdd46750c0fda97d30c65442807cfbf5f03e3b3e04b"))

