-- generated by definy. Do not edit!
module CreativeRecord.Origin (origin) where

import Data.String.NonEmpty as NonEmptyString
import Type.Proxy as Proxy

-- | アプリケーションのオリジン (コード生成結果)
origin :: NonEmptyString.NonEmptyString
origin = NonEmptyString.nes (Proxy.Proxy :: Proxy.Proxy "http://localhost:1234")
