-- generated by definy. Do not edit!
module CreativeRecord.Origin(origin) where

import Data.String.NonEmpty as M0
import Type.Proxy as M1

-- | アプリケーションのオリジン (コード生成結果)
origin :: M0.NonEmptyString
origin = (M0.nes) (M1.Proxy :: M1.Proxy ("http://localhost:1324"))

