-- generated by definy. Do not edit!
module CreativeRecord.StaticResource(battlePng, colorPng, definy20210811Png, desired_route_titlePng, fontPng, grape_svg_codePng, gravity_starPng, henkanPng, iconPng, kamausagiPng, list_uiPng, powershell_iconPng, starPng, svg_basicPng, tsukumartPng, windowPng) where

import Data.Map as M0
import Data.String.NonEmpty as M1
import StructuredUrl as M2
import Type.Proxy as M3

-- | static な ファイル の `./narumincho-creative-record/resource/battle.png` をリクエストするためのURL. ファイルのハッシュ値は `d0d5b5155e3bf151182dec717b40219b2e3eeb3ddf0c00788ae09ae81e835a98`(コード生成結果)
battlePng :: M2.PathAndSearchParams
battlePng = (M2.pathAndSearchParams) ([ (M1.nes) (M3.Proxy :: M3.Proxy ("d0d5b5155e3bf151182dec717b40219b2e3eeb3ddf0c00788ae09ae81e835a98")) ]) (M0.empty)

-- | static な ファイル の `./narumincho-creative-record/resource/color.png` をリクエストするためのURL. ファイルのハッシュ値は `69cb9776df6fe254459a0777072c1ba1b613cac6a29bd038cb9bb5ffdbc930e2`(コード生成結果)
colorPng :: M2.PathAndSearchParams
colorPng = (M2.pathAndSearchParams) ([ (M1.nes) (M3.Proxy :: M3.Proxy ("69cb9776df6fe254459a0777072c1ba1b613cac6a29bd038cb9bb5ffdbc930e2")) ]) (M0.empty)

-- | static な ファイル の `./narumincho-creative-record/resource/definy20210811.png` をリクエストするためのURL. ファイルのハッシュ値は `0120c597af9fca9ba96ebcabfb4cf2c7a3487d6032c43e0665b06438d71a002b`(コード生成結果)
definy20210811Png :: M2.PathAndSearchParams
definy20210811Png = (M2.pathAndSearchParams) ([ (M1.nes) (M3.Proxy :: M3.Proxy ("0120c597af9fca9ba96ebcabfb4cf2c7a3487d6032c43e0665b06438d71a002b")) ]) (M0.empty)

-- | static な ファイル の `./narumincho-creative-record/resource/desired_route_title.png` をリクエストするためのURL. ファイルのハッシュ値は `c273cd987dd17e47754ed882b9e90d3db3f239d277835f40f7914ea19272fbcc`(コード生成結果)
desired_route_titlePng :: M2.PathAndSearchParams
desired_route_titlePng = (M2.pathAndSearchParams) ([ (M1.nes) (M3.Proxy :: M3.Proxy ("c273cd987dd17e47754ed882b9e90d3db3f239d277835f40f7914ea19272fbcc")) ]) (M0.empty)

-- | static な ファイル の `./narumincho-creative-record/resource/font.png` をリクエストするためのURL. ファイルのハッシュ値は `9eafa059786cc013afb3adcc40f0b932384e95b37b788b2f50dceadba9756217`(コード生成結果)
fontPng :: M2.PathAndSearchParams
fontPng = (M2.pathAndSearchParams) ([ (M1.nes) (M3.Proxy :: M3.Proxy ("9eafa059786cc013afb3adcc40f0b932384e95b37b788b2f50dceadba9756217")) ]) (M0.empty)

-- | static な ファイル の `./narumincho-creative-record/resource/grape_svg_code.png` をリクエストするためのURL. ファイルのハッシュ値は `4b330bb7de6534c6fc3ed51a952d41e7469f329efd729b8fa5b8e3250cc4b1f0`(コード生成結果)
grape_svg_codePng :: M2.PathAndSearchParams
grape_svg_codePng = (M2.pathAndSearchParams) ([ (M1.nes) (M3.Proxy :: M3.Proxy ("4b330bb7de6534c6fc3ed51a952d41e7469f329efd729b8fa5b8e3250cc4b1f0")) ]) (M0.empty)

-- | static な ファイル の `./narumincho-creative-record/resource/gravity_star.png` をリクエストするためのURL. ファイルのハッシュ値は `fbd8d22e751dfa4839801f57291c988ae1ae34e87801d0fa352c67974a513a7e`(コード生成結果)
gravity_starPng :: M2.PathAndSearchParams
gravity_starPng = (M2.pathAndSearchParams) ([ (M1.nes) (M3.Proxy :: M3.Proxy ("fbd8d22e751dfa4839801f57291c988ae1ae34e87801d0fa352c67974a513a7e")) ]) (M0.empty)

-- | static な ファイル の `./narumincho-creative-record/resource/henkan.png` をリクエストするためのURL. ファイルのハッシュ値は `65cc89888994728d91dfc23caee830d5d07a66baf043fd3a536dbed24da26d0a`(コード生成結果)
henkanPng :: M2.PathAndSearchParams
henkanPng = (M2.pathAndSearchParams) ([ (M1.nes) (M3.Proxy :: M3.Proxy ("65cc89888994728d91dfc23caee830d5d07a66baf043fd3a536dbed24da26d0a")) ]) (M0.empty)

-- | static な ファイル の `./narumincho-creative-record/resource/icon.png` をリクエストするためのURL. ファイルのハッシュ値は `098f526733f0a87c33e598f953769a7fa86fcffca5072011bba21ffb007ca7f5`(コード生成結果)
iconPng :: M2.PathAndSearchParams
iconPng = (M2.pathAndSearchParams) ([ (M1.nes) (M3.Proxy :: M3.Proxy ("098f526733f0a87c33e598f953769a7fa86fcffca5072011bba21ffb007ca7f5")) ]) (M0.empty)

-- | static な ファイル の `./narumincho-creative-record/resource/kamausagi.png` をリクエストするためのURL. ファイルのハッシュ値は `195b56c3a78e4fdf2441ffc1eb10aef1034d4162d49109913f791cb971b5febc`(コード生成結果)
kamausagiPng :: M2.PathAndSearchParams
kamausagiPng = (M2.pathAndSearchParams) ([ (M1.nes) (M3.Proxy :: M3.Proxy ("195b56c3a78e4fdf2441ffc1eb10aef1034d4162d49109913f791cb971b5febc")) ]) (M0.empty)

-- | static な ファイル の `./narumincho-creative-record/resource/list_ui.png` をリクエストするためのURL. ファイルのハッシュ値は `36a91f221e48405c2ee2b574ccbfe9c727c4e1932384d505530afbfd7f3bac00`(コード生成結果)
list_uiPng :: M2.PathAndSearchParams
list_uiPng = (M2.pathAndSearchParams) ([ (M1.nes) (M3.Proxy :: M3.Proxy ("36a91f221e48405c2ee2b574ccbfe9c727c4e1932384d505530afbfd7f3bac00")) ]) (M0.empty)

-- | static な ファイル の `./narumincho-creative-record/resource/powershell_icon.png` をリクエストするためのURL. ファイルのハッシュ値は `c108fea0178ded573bed955a633d681dd2c15e2fd8ea45556b2ee1bea8688cf9`(コード生成結果)
powershell_iconPng :: M2.PathAndSearchParams
powershell_iconPng = (M2.pathAndSearchParams) ([ (M1.nes) (M3.Proxy :: M3.Proxy ("c108fea0178ded573bed955a633d681dd2c15e2fd8ea45556b2ee1bea8688cf9")) ]) (M0.empty)

-- | static な ファイル の `./narumincho-creative-record/resource/star.png` をリクエストするためのURL. ファイルのハッシュ値は `3e875e3e5caedcf07d6e8416c065b0bef5383e4523d8968f8348db52bab549ef`(コード生成結果)
starPng :: M2.PathAndSearchParams
starPng = (M2.pathAndSearchParams) ([ (M1.nes) (M3.Proxy :: M3.Proxy ("3e875e3e5caedcf07d6e8416c065b0bef5383e4523d8968f8348db52bab549ef")) ]) (M0.empty)

-- | static な ファイル の `./narumincho-creative-record/resource/svg_basic.png` をリクエストするためのURL. ファイルのハッシュ値は `4759c2725203a86dd60e95f1ec169d400c580ed9726f90cbb43cc147e38b35da`(コード生成結果)
svg_basicPng :: M2.PathAndSearchParams
svg_basicPng = (M2.pathAndSearchParams) ([ (M1.nes) (M3.Proxy :: M3.Proxy ("4759c2725203a86dd60e95f1ec169d400c580ed9726f90cbb43cc147e38b35da")) ]) (M0.empty)

-- | static な ファイル の `./narumincho-creative-record/resource/tsukumart.png` をリクエストするためのURL. ファイルのハッシュ値は `f72f6883b8f091e28c26e64d8b755e689a43848351d6087aa66ec990372a9bd1`(コード生成結果)
tsukumartPng :: M2.PathAndSearchParams
tsukumartPng = (M2.pathAndSearchParams) ([ (M1.nes) (M3.Proxy :: M3.Proxy ("f72f6883b8f091e28c26e64d8b755e689a43848351d6087aa66ec990372a9bd1")) ]) (M0.empty)

-- | static な ファイル の `./narumincho-creative-record/resource/window.png` をリクエストするためのURL. ファイルのハッシュ値は `37a5d840bc6be92b9c45f859b8a33d7518e071cfb7fb851a1938bb86680fa0d2`(コード生成結果)
windowPng :: M2.PathAndSearchParams
windowPng = (M2.pathAndSearchParams) ([ (M1.nes) (M3.Proxy :: M3.Proxy ("37a5d840bc6be92b9c45f859b8a33d7518e071cfb7fb851a1938bb86680fa0d2")) ]) (M0.empty)

