-- generated by definy. Do not edit!

module CreativeRecord.StaticResource(battlePng, colorPng, definy20210811Png, desired_route_titlePng, fontPng, grape_svg_codePng, gravity_starPng, henkanPng, iconPng, kamausagiPng, list_uiPng, powershell_iconPng, starPng, svg_basicPng, tsukumartPng, windowPng) where

import Data.Map as M0
import Prim as M1
import StructuredUrl as M2

-- | static な ファイル の "./narumincho-creative-record/resource/battle.png"をリクエストするためのURL. ファイルのハッシュ値は b498aff8917d349aa0f9b3a41a0d6a5b7093caea175873b4bc77a467ef67d499"(コード生成結果)
battlePng :: M1.String
battlePng = (M2.pathAndSearchParams) ([ "b498aff8917d349aa0f9b3a41a0d6a5b7093caea175873b4bc77a467ef67d499" ]) (M0.empty)

-- | static な ファイル の "./narumincho-creative-record/resource/color.png"をリクエストするためのURL. ファイルのハッシュ値は d1f295174ec13a77811ff1b9e4c58377f50c444ba1bea8f9587448f2720c655c"(コード生成結果)
colorPng :: M1.String
colorPng = (M2.pathAndSearchParams) ([ "d1f295174ec13a77811ff1b9e4c58377f50c444ba1bea8f9587448f2720c655c" ]) (M0.empty)

-- | static な ファイル の "./narumincho-creative-record/resource/definy20210811.png"をリクエストするためのURL. ファイルのハッシュ値は 33b80a0844230e60044b9891dc2fbefc3960e7995913e10928ca17852a8c3ce7"(コード生成結果)
definy20210811Png :: M1.String
definy20210811Png = (M2.pathAndSearchParams) ([ "33b80a0844230e60044b9891dc2fbefc3960e7995913e10928ca17852a8c3ce7" ]) (M0.empty)

-- | static な ファイル の "./narumincho-creative-record/resource/desired_route_title.png"をリクエストするためのURL. ファイルのハッシュ値は 6959cae6bdab07e752157c9077d1153b0a61d525869b7ecef6630b8cde4815b0"(コード生成結果)
desired_route_titlePng :: M1.String
desired_route_titlePng = (M2.pathAndSearchParams) ([ "6959cae6bdab07e752157c9077d1153b0a61d525869b7ecef6630b8cde4815b0" ]) (M0.empty)

-- | static な ファイル の "./narumincho-creative-record/resource/font.png"をリクエストするためのURL. ファイルのハッシュ値は 68c380d905ce9e1f8043c3f5c3c7f3fd51b0156d49cd36912aaf94c7f368c28a"(コード生成結果)
fontPng :: M1.String
fontPng = (M2.pathAndSearchParams) ([ "68c380d905ce9e1f8043c3f5c3c7f3fd51b0156d49cd36912aaf94c7f368c28a" ]) (M0.empty)

-- | static な ファイル の "./narumincho-creative-record/resource/grape_svg_code.png"をリクエストするためのURL. ファイルのハッシュ値は ddc034ae2b5d07e6ec33076a3a45bd9772c6670f53b14ddd30c0b51f2b97c7fb"(コード生成結果)
grape_svg_codePng :: M1.String
grape_svg_codePng = (M2.pathAndSearchParams) ([ "ddc034ae2b5d07e6ec33076a3a45bd9772c6670f53b14ddd30c0b51f2b97c7fb" ]) (M0.empty)

-- | static な ファイル の "./narumincho-creative-record/resource/gravity_star.png"をリクエストするためのURL. ファイルのハッシュ値は 68800d65e7bba25db6a2e5e5d2001e275969f10e653d34233989543090809dc2"(コード生成結果)
gravity_starPng :: M1.String
gravity_starPng = (M2.pathAndSearchParams) ([ "68800d65e7bba25db6a2e5e5d2001e275969f10e653d34233989543090809dc2" ]) (M0.empty)

-- | static な ファイル の "./narumincho-creative-record/resource/henkan.png"をリクエストするためのURL. ファイルのハッシュ値は fbeaa96a4aa8321b5f81238cad963e5e2eb1a8ef8f39f169b5a015bca7f06bb2"(コード生成結果)
henkanPng :: M1.String
henkanPng = (M2.pathAndSearchParams) ([ "fbeaa96a4aa8321b5f81238cad963e5e2eb1a8ef8f39f169b5a015bca7f06bb2" ]) (M0.empty)

-- | static な ファイル の "./narumincho-creative-record/resource/icon.png"をリクエストするためのURL. ファイルのハッシュ値は fe793a7f2e27cb8cfe578e5dff35315e2ba9c2544dcb250d3e9b78ca00a5b959"(コード生成結果)
iconPng :: M1.String
iconPng = (M2.pathAndSearchParams) ([ "fe793a7f2e27cb8cfe578e5dff35315e2ba9c2544dcb250d3e9b78ca00a5b959" ]) (M0.empty)

-- | static な ファイル の "./narumincho-creative-record/resource/kamausagi.png"をリクエストするためのURL. ファイルのハッシュ値は 6939a60eff9d66c18333d1cd28cdb052ed5d6ed8e0c933b9bfa2780596f41853"(コード生成結果)
kamausagiPng :: M1.String
kamausagiPng = (M2.pathAndSearchParams) ([ "6939a60eff9d66c18333d1cd28cdb052ed5d6ed8e0c933b9bfa2780596f41853" ]) (M0.empty)

-- | static な ファイル の "./narumincho-creative-record/resource/list_ui.png"をリクエストするためのURL. ファイルのハッシュ値は 7d1f910bbaccf3362282d509b606084ca93b8e2dd8055283280b421ae5d5c50a"(コード生成結果)
list_uiPng :: M1.String
list_uiPng = (M2.pathAndSearchParams) ([ "7d1f910bbaccf3362282d509b606084ca93b8e2dd8055283280b421ae5d5c50a" ]) (M0.empty)

-- | static な ファイル の "./narumincho-creative-record/resource/powershell_icon.png"をリクエストするためのURL. ファイルのハッシュ値は 3e53209d83848dffa23b7cbbdca35a735c55a6b55601cdedd303a3f90d559fe3"(コード生成結果)
powershell_iconPng :: M1.String
powershell_iconPng = (M2.pathAndSearchParams) ([ "3e53209d83848dffa23b7cbbdca35a735c55a6b55601cdedd303a3f90d559fe3" ]) (M0.empty)

-- | static な ファイル の "./narumincho-creative-record/resource/star.png"をリクエストするためのURL. ファイルのハッシュ値は f0e7afe9457c2dc0c117934e3e584001d1fa7c910ec912ac1260179ab1dac8db"(コード生成結果)
starPng :: M1.String
starPng = (M2.pathAndSearchParams) ([ "f0e7afe9457c2dc0c117934e3e584001d1fa7c910ec912ac1260179ab1dac8db" ]) (M0.empty)

-- | static な ファイル の "./narumincho-creative-record/resource/svg_basic.png"をリクエストするためのURL. ファイルのハッシュ値は 07eb3d10e2f339ab8574ffa8a3f9f15bfd6f51518ef24bb38ae92d54deb9510a"(コード生成結果)
svg_basicPng :: M1.String
svg_basicPng = (M2.pathAndSearchParams) ([ "07eb3d10e2f339ab8574ffa8a3f9f15bfd6f51518ef24bb38ae92d54deb9510a" ]) (M0.empty)

-- | static な ファイル の "./narumincho-creative-record/resource/tsukumart.png"をリクエストするためのURL. ファイルのハッシュ値は 2df345d24aef7080b8f64a69a022b8e1d7968ebfd8e93e42c1c6e7a9cb088d64"(コード生成結果)
tsukumartPng :: M1.String
tsukumartPng = (M2.pathAndSearchParams) ([ "2df345d24aef7080b8f64a69a022b8e1d7968ebfd8e93e42c1c6e7a9cb088d64" ]) (M0.empty)

-- | static な ファイル の "./narumincho-creative-record/resource/window.png"をリクエストするためのURL. ファイルのハッシュ値は 3162cd943ef3c3c7681b84acb99e54ada924dccdbcda8ee090d31e28efda1dc8"(コード生成結果)
windowPng :: M1.String
windowPng = (M2.pathAndSearchParams) ([ "3162cd943ef3c3c7681b84acb99e54ada924dccdbcda8ee090d31e28efda1dc8" ]) (M0.empty)

