/* eslint-disable */
/* generated by definy. Do not edit! */


/**
 * モジュールの説明だよー
 */


/**
 * partDescription
 */
export const _ = (1.0+(2.0+3.0));


/**
 * **サンプル4パーツの説明文!**
 */
export const sample4Part = (3.0+1.0);


/**
 * samplePartの説明文 カッコ() や 空白を含めることもできるようになったぞ!
 */
export const samplePart = (sample4Part+10.0);


/**
 * bの説明文 改行有り
 */
export const b = (samplePart+1.0);


/**
 * kの説明文
 */
export const k = (samplePart+(1.0+39.0));


/**
 * description
 */
export const sample = 123.0;


/**
 * description
 */
export const sample = ("<unknown part!!!>"+28.0);
