/* eslint-disable */
/* generated by definy. Do not edit! */


/**
 * 分かりやすい説明文
 */


/**
 * 浮動小数点数のサンプル
 */
export const floatSample = 32;


/**
 * part description
 */
export const partName = 6.28;


/**
 * part description
 */
export const partName = "テキスト";
