/* eslint-disable */
/* generated by definy. Do not edit! */


/**
 * mimetype
 */


/**
 * png 画像
 */
export const png = "image/png";


/**
 * html
 */
export const html = "text/html";


/**
 * javaScript
 */
export const javaScript = "text/javaScript";


/**
 * json
 */
export const json = "application/json";


/**
 * フォント WebOpenFontFormat2
 */
export const woff2 = "font/woff2";


/**
 * バイナリ形式
 */
export const binary = "application/octet-stream";
