// このファイルは narumincho-vdom-build によって自動生成されました。
use crate::Element;

pub struct button {

    pub id: Option<String>,
    pub anchor: Option<String>,
    pub class: Option<String>,
    pub is: Option<String>,
    pub autofocus: Option<String>,
    pub popover: Option<String>,
    pub inert: Option<String>,
    pub slot: Option<String>,
    pub hidden: Option<String>,
    pub autocorrect: Option<String>,
    pub lang: Option<String>,
    pub title: Option<String>,
    pub enterkeyhint: Option<String>,
    pub contenteditable: Option<String>,
    pub writingsuggestions: Option<String>,
    pub data_attributes: Option<String>,
    pub style: Option<String>,
    pub nonce: Option<String>,
    pub accesskey: Option<String>,
    pub draggable: Option<String>,
    pub exportparts: Option<String>,
    pub inputmode: Option<String>,
    pub part: Option<String>,
    pub dir: Option<String>,
    pub autocapitalize: Option<String>,
    pub tabindex: Option<String>,
    pub spellcheck: Option<String>,
    pub virtualkeyboardpolicy: Option<String>,
    pub translate: Option<String>,
    pub popovertarget: Option<String>,
    pub formaction: Option<String>,
    pub formtarget: Option<String>,
    pub command: Option<String>,
    pub formnovalidate: Option<String>,
    pub disabled: Option<String>,
    pub formmethod: Option<String>,
    pub form: Option<String>,
    pub commandfor: Option<String>,
    pub formenctype: Option<String>,
    pub popovertargetaction: Option<String>,
    pub r#type: Option<String>,
    pub name: Option<String>,
    pub interestfor: Option<String>,
    pub value: Option<String>,
}


