// このファイルは narumincho-vdom-build によって自動生成されました。
use crate::Element;

pub struct datalist {

    pub id: Option<String>,
    pub anchor: Option<String>,
    pub class: Option<String>,
    pub is: Option<String>,
    pub autofocus: Option<String>,
    pub popover: Option<String>,
    pub inert: Option<String>,
    pub slot: Option<String>,
    pub hidden: Option<String>,
    pub autocorrect: Option<String>,
    pub lang: Option<String>,
    pub title: Option<String>,
    pub enterkeyhint: Option<String>,
    pub contenteditable: Option<String>,
    pub writingsuggestions: Option<String>,
    pub data_attributes: Option<String>,
    pub style: Option<String>,
    pub nonce: Option<String>,
    pub accesskey: Option<String>,
    pub draggable: Option<String>,
    pub exportparts: Option<String>,
    pub inputmode: Option<String>,
    pub part: Option<String>,
    pub dir: Option<String>,
    pub autocapitalize: Option<String>,
    pub tabindex: Option<String>,
    pub spellcheck: Option<String>,
    pub virtualkeyboardpolicy: Option<String>,
    pub translate: Option<String>,
    pub input_type_time: Option<String>,
    pub input_type_date: Option<String>,
    pub input_type_number: Option<String>,
    pub input_type_url: Option<String>,
    pub input_type_color: Option<String>,
    pub input_type_email: Option<String>,
    pub input_type_range: Option<String>,
    pub input_type_search: Option<String>,
    pub input_type_tel: Option<String>,
    pub input_type_text: Option<String>,
}


