// このファイルは narumincho-vdom-build によって自動生成されました。
use crate::Element;

pub struct iframe {

    pub id: Option<String>,
    pub anchor: Option<String>,
    pub class: Option<String>,
    pub is: Option<String>,
    pub autofocus: Option<String>,
    pub popover: Option<String>,
    pub inert: Option<String>,
    pub slot: Option<String>,
    pub hidden: Option<String>,
    pub autocorrect: Option<String>,
    pub lang: Option<String>,
    pub title: Option<String>,
    pub enterkeyhint: Option<String>,
    pub contenteditable: Option<String>,
    pub writingsuggestions: Option<String>,
    pub data_attributes: Option<String>,
    pub style: Option<String>,
    pub nonce: Option<String>,
    pub accesskey: Option<String>,
    pub draggable: Option<String>,
    pub exportparts: Option<String>,
    pub inputmode: Option<String>,
    pub part: Option<String>,
    pub dir: Option<String>,
    pub autocapitalize: Option<String>,
    pub tabindex: Option<String>,
    pub spellcheck: Option<String>,
    pub virtualkeyboardpolicy: Option<String>,
    pub translate: Option<String>,
    pub align: Option<String>,
    pub privateToken: Option<String>,
    pub referrerpolicy: Option<String>,
    pub width: Option<String>,
    pub loading: Option<String>,
    pub name: Option<String>,
    pub src: Option<String>,
    pub srcdoc: Option<String>,
    pub sandbox: Option<String>,
    pub marginheight: Option<String>,
    pub allowfullscreen: Option<String>,
    pub longdesc: Option<String>,
    pub allowpaymentrequest: Option<String>,
    pub browsingtopics: Option<String>,
    pub csp: Option<String>,
    pub scrolling: Option<String>,
    pub frameborder: Option<String>,
    pub allow: Option<String>,
    pub cross_origin_top_navigation_by_user_activation: Option<String>,
    pub credentialless: Option<String>,
    pub marginwidth: Option<String>,
    pub height: Option<String>,
}


