// このファイルは narumincho-vdom-build によって自動生成されました。
use crate::Element;

pub struct img {

    pub id: Option<String>,
    pub anchor: Option<String>,
    pub class: Option<String>,
    pub is: Option<String>,
    pub autofocus: Option<String>,
    pub popover: Option<String>,
    pub inert: Option<String>,
    pub slot: Option<String>,
    pub hidden: Option<String>,
    pub autocorrect: Option<String>,
    pub lang: Option<String>,
    pub title: Option<String>,
    pub enterkeyhint: Option<String>,
    pub contenteditable: Option<String>,
    pub writingsuggestions: Option<String>,
    pub data_attributes: Option<String>,
    pub style: Option<String>,
    pub nonce: Option<String>,
    pub accesskey: Option<String>,
    pub draggable: Option<String>,
    pub exportparts: Option<String>,
    pub inputmode: Option<String>,
    pub part: Option<String>,
    pub dir: Option<String>,
    pub autocapitalize: Option<String>,
    pub tabindex: Option<String>,
    pub spellcheck: Option<String>,
    pub virtualkeyboardpolicy: Option<String>,
    pub translate: Option<String>,
    pub loading: Option<String>,
    pub alt: Option<String>,
    pub name: Option<String>,
    pub ismap: Option<String>,
    pub decoding: Option<String>,
    pub src: Option<String>,
    pub align: Option<String>,
    pub aspect_ratio_computed_from_attributes: Option<String>,
    pub crossorigin: Option<String>,
    pub referrerpolicy: Option<String>,
    pub height: Option<String>,
    pub hspace: Option<String>,
    pub sizes: Option<String>,
    pub usemap: Option<String>,
    pub srcset: Option<String>,
    pub width: Option<String>,
    pub attributionsrc: Option<String>,
    pub fetchpriority: Option<String>,
    pub vspace: Option<String>,
    pub longdesc: Option<String>,
    pub border: Option<String>,
}


