// このファイルは narumincho-vdom-build によって自動生成されました。
use crate::Element;

pub struct link {

    pub id: Option<String>,
    pub anchor: Option<String>,
    pub class: Option<String>,
    pub is: Option<String>,
    pub autofocus: Option<String>,
    pub popover: Option<String>,
    pub inert: Option<String>,
    pub slot: Option<String>,
    pub hidden: Option<String>,
    pub autocorrect: Option<String>,
    pub lang: Option<String>,
    pub title: Option<String>,
    pub enterkeyhint: Option<String>,
    pub contenteditable: Option<String>,
    pub writingsuggestions: Option<String>,
    pub data_attributes: Option<String>,
    pub style: Option<String>,
    pub nonce: Option<String>,
    pub accesskey: Option<String>,
    pub draggable: Option<String>,
    pub exportparts: Option<String>,
    pub inputmode: Option<String>,
    pub part: Option<String>,
    pub dir: Option<String>,
    pub autocapitalize: Option<String>,
    pub tabindex: Option<String>,
    pub spellcheck: Option<String>,
    pub virtualkeyboardpolicy: Option<String>,
    pub translate: Option<String>,
    pub imagesizes: Option<String>,
    pub imagesrcset: Option<String>,
    pub target: Option<String>,
    pub r#type: Option<String>,
    pub media: Option<String>,
    pub r#type: Option<String>,
    pub integrity: Option<String>,
    pub fetchpriority: Option<String>,
    pub rel: Option<String>,
    pub blocking: Option<String>,
    pub href: Option<String>,
    pub referrerpolicy: Option<String>,
    pub rev: Option<String>,
    pub charset: Option<String>,
    pub crossorigin: Option<String>,
    pub disabled: Option<String>,
    pub sizes: Option<String>,
    pub hreflang: Option<String>,
}


