// このファイルは narumincho-vdom-build によって自動生成されました。
use crate::Element;

pub struct table {

    pub id: Option<String>,
    pub anchor: Option<String>,
    pub class: Option<String>,
    pub is: Option<String>,
    pub autofocus: Option<String>,
    pub popover: Option<String>,
    pub inert: Option<String>,
    pub slot: Option<String>,
    pub hidden: Option<String>,
    pub autocorrect: Option<String>,
    pub lang: Option<String>,
    pub title: Option<String>,
    pub enterkeyhint: Option<String>,
    pub contenteditable: Option<String>,
    pub writingsuggestions: Option<String>,
    pub data_attributes: Option<String>,
    pub style: Option<String>,
    pub nonce: Option<String>,
    pub accesskey: Option<String>,
    pub draggable: Option<String>,
    pub exportparts: Option<String>,
    pub inputmode: Option<String>,
    pub part: Option<String>,
    pub dir: Option<String>,
    pub autocapitalize: Option<String>,
    pub tabindex: Option<String>,
    pub spellcheck: Option<String>,
    pub virtualkeyboardpolicy: Option<String>,
    pub translate: Option<String>,
    pub border: Option<String>,
    pub align: Option<String>,
    pub width: Option<String>,
    pub rules: Option<String>,
    pub bgcolor: Option<String>,
    pub cellspacing: Option<String>,
    pub cellpadding: Option<String>,
    pub summary: Option<String>,
    pub frame: Option<String>,
}


