import * as d from "./data.ts";
import {
  documentToString,
  typeParameterListToString,
} from "./toString/common.ts";
import { exprToString, lambdaBodyToString } from "./toString/expr.ts";
import { typeAnnotation, typeToString } from "./toString/type.ts";
import { statementListToString } from "./toString/statement.ts";
import { Context } from "./toString/context.ts";

/**
 * コードを文字列にする
 */
export const toString = (
  code: d.JsTsCode,
  context: Context,
): string => {
  const importCode =
    "/* eslint-disable */\n/* generated by definy. Do not edit! */\n\n" +
    [...context.moduleMap.entries()]
      .map(
        ([name, identifier]) =>
          "import * as " + identifier + ' from "' + name + '";',
      )
      .join("\n") +
    "\n";

  const definitionCode = code.exportDefinitionList
    .map((definition) => definitionToString(definition, context))
    .join("") + "\n";

  const statementCode = statementListToString(
    code.statementList,
    0,
    context,
  );

  if (code.statementList.length === 0) {
    return importCode + definitionCode;
  }
  return importCode + definitionCode + statementCode;
};

const definitionToString = (
  definition: d.ExportDefinition,
  context: Context,
): string => {
  switch (definition.type) {
    case "typeAlias":
      if (context.codeType === "JavaScript") {
        return "";
      }
      return typeAliasToString(definition.typeAlias, context);

    case "function":
      return exportFunctionToString(definition.function, context);

    case "variable":
      return exportVariableToString(definition.variable, context);
  }
};

const typeAliasToString = (
  typeAlias: d.TypeAlias,
  context: Context,
): string => {
  const content = documentToString(typeAlias.document) +
    "export type " +
    typeAlias.name +
    typeParameterListToString(typeAlias.typeParameterList) +
    " = " +
    typeToString(typeAlias.type, context) +
    ";\n\n";
  if (typeAlias.namespace.length === 0) {
    return content;
  }
  return (
    "export declare namespace " +
    typeAlias.namespace.join(".") +
    " {\n" +
    content +
    "\n}"
  );
};

const exportFunctionToString = (
  function_: d.Function,
  context: Context,
): string =>
  documentToString(
    function_.document + parameterListToDocument(function_.parameterList),
  ) +
  "export const " +
  function_.name +
  " = " +
  typeParameterListToString(function_.typeParameterList) +
  "(" +
  function_.parameterList
    .map(
      (parameter) => parameter.name + typeAnnotation(parameter.type, context),
    )
    .join(", ") +
  ")" +
  typeAnnotation(function_.returnType, context) +
  " => " +
  lambdaBodyToString(function_.statementList, 0, context) +
  ";\n\n";

const exportVariableToString = (
  variable: d.Variable,
  context: Context,
): string =>
  documentToString(variable.document) +
  (variable.private ? "" : "export ") +
  "const " +
  variable.name +
  (variable.type === undefined ? "" : typeAnnotation(variable.type, context)) +
  " = " +
  exprToString(variable.expr, 0, context) +
  ";\n\n";

const parameterListToDocument = (
  parameterList: ReadonlyArray<d.ParameterWithDocument>,
): string =>
  parameterList.length === 0 ? "" : "\n" +
    parameterList
      .map((parameter) =>
        parameter.document === ""
          ? ""
          : "@param " + parameter.name + " " + parameter.document
      )
      .join("\n");
