[package]
name = "definy-event"
version = "0.1.0"
edition = "2024"

[features]
default = []
utoipa = ["dep:utoipa"]
schemars = ["dep:schemars"]

[dependencies]
utoipa = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
chrono = { workspace = true, features = ["alloc", "serde", "wasmbind", "now"] }
serde = { workspace = true, features = ["derive"] }
serde_cbor = { workspace = true, features = ["std", "tags"] }
ed25519-dalek = { workspace = true, features = ["rand_core", "serde"] }
anyhow = { workspace = true }
strum_macros = { workspace = true }
strum = { workspace = true, features = ["derive"] }
sha2 = { workspace = true }
base64 = { workspace = true }
prost = { workspace = true }

[dev-dependencies]
rand_core = { workspace = true, features = ["getrandom"] }
serde_json = { workspace = true }
schemars = { workspace = true }
