name: Deploy to Firebase (narumincho-com-dev)

on:
  push:
    branches: main

jobs:
  build-and-deploy:
    name: build and deploy
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install npm dependencies (npm ci)
        run: npm ci
      - name: PureScript Build
        run: npx spago build
      - name: Run build script
        run: npm run build-narumincho-creative-record
      - name: Deploy to Firebase
        run: npx firebase deploy --config ./distribution/creative-record/firebase.json --project narumincho-com-dev --token ${{ secrets.FIREBASE_TOKEN }}
