name: deploy node package

on: workflow_dispatch

jobs:
  npm-publish:
    name: npm publish
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install npm dependencies (npm ci)
        run: npm ci
      - name: Run Build Script
        run: npm run build-gen
      - name: npm publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          package: ./distribution/npm-package/package.json
