name: deploy to vercel

on: push

jobs:
  deploy-to-vercel:
    name: deploy to vercel
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
      - run: corepack enable
      - name: setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.28.1
      - name: Install npm dependencies (pnpm install)
        run: pnpm install --frozen-lockfile
      - name: Deno to Node.js
        run: deno run -A ./build.ts
        working-directory: ./deno-lib
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
