name: Deploy to Firebase (definy-dev)

on:
  push:
    branches: [dev]

jobs:
  build-and-deploy:
    name: build and deploy
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: pnpm
      - run: corepack enable
      - name: Install npm dependencies
        run: pnpm install
      - name: PureScript FFI Code TypeScript → JavaScript
        run: npx tsc --project ./tsconfig-purs-ffi.json
      - name: PureScript Build
        run: npx spago build
      - name: Run build script
        run: npx spago run --main Definy.StartProductionDev
      - name: Deploy to Firebase
        run: npx firebase deploy --config ./distribution/definy/firebase.json --project definy-dev --token ${{ secrets.FIREBASE_TOKEN }}
