name: deploy vercel

on: push

jobs:
  npm-publish:
    name: npm publish
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: corepack enable
      - name: setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.26.1
      - name: Install npm dependencies (pnpm install)
        run: pnpm install
      - name: Deno to Node.js
        run: deno run -A ./build.ts
        working-directory: ./deno-lib
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
