name: deploy node package

on: workflow_dispatch

jobs:
  npm-publish:
    name: npm publish
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: corepack enable
      - name: Install npm dependencies (pnpm install)
        run: pnpm install
      - name: Run Build Script
        run: npm run build-node-package
      - name: npm publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          package: ./distribution/npm-package/package.json
